package GameOfChance;
public class SplashScreen extends javax.swing.JFrame {
void Splash(){
        try{
        for(int x=0;x<=100;x++){
            Thread.sleep(30);
            pp.setText(Integer.toString(x)+"%");
            pbar.setValue(x);
            
        }
        }catch(Exception e){   
        }
        this.dispose();  
        try{
            Thread.sleep(170);
        }catch(Exception e){
        } 
        Main LinkMain=new Main();
        LinkMain.setVisible(true);
    }
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        pbar = new javax.swing.JProgressBar();
        pp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(410, 300));
        setUndecorated(true);

        jDesktopPane1.setMinimumSize(new java.awt.Dimension(410, 300));
        jDesktopPane1.setOpaque(false);

        pbar.setBackground(new java.awt.Color(226, 242, 251));
        pbar.setForeground(new java.awt.Color(233, 18, 55));
        jDesktopPane1.add(pbar);
        pbar.setBounds(10, 180, 220, 14);

        pp.setBackground(new java.awt.Color(255, 255, 255));
        pp.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        pp.setForeground(new java.awt.Color(233, 18, 55));
        pp.setText("0%");
        jDesktopPane1.add(pp);
        pp.setBounds(90, 210, 60, 30);

        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 18, 55));
        jLabel2.setText("Game Of Chance");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(60, 10, 274, 54);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GameOfChance/splsh.png"))); // NOI18N
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(0, 0, 410, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar pbar;
    private javax.swing.JLabel pp;
    // End of variables declaration//GEN-END:variables
}
